# Sets up everything needed to deploy Docker images with CDK.
# It deploys everything that is not specific to a certain environment (such as staging or prod).
# It should be a one-off workflow run.

name: 01 - Manually bootstrap the CDK Environment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Bootstrap CDK setup
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: NPM install
        run: npm install

      - name: Deploy CDK bootstrap stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          npm run bootstrap
      - name: Deploy Docker repository
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
        run: |
          npm run repository:deploy -- -c accountId=${{ secrets.AWS_ACCOUNT_ID }} -c region=${{ secrets.AWS_DEPLOY_REGION }}
